# Binning

## Contexto

O passo de binning se trata do processo de agrupar sequências montadas da metagenômica (contigs/scaffolds) que provavelmente pertencem ao mesmo organismo.

!(images/binning.png)

## Arquivos e ambiente conda necessários {#sec-bdalign}
Desative o ambiente conda "metagenomicsTraining'
```bash
conda deactivate
```
Ative o ambiente conda "binning"
```bash
conda activate binning
```
Arquivos necessários:

```bash
final.contigs.fa
SRR579292_1.fastq
SRR579292_2.fastq
```

Mude o diretório atual para `"Pipeline/data/megahit/SRR579292"`

## Preparativos para a execução dos softwares de binning

Faça a indexação dos contigs

```bash
bowtie2-build final.contigs.fa contigs_db
```

Mapeie as reads:

```bash
bowtie2 -x contigs_db -1 ../../SRR579292_1.fastq -2 ../../SRR579292_2.fastq -p 12 | samtools view -bS - | samtools sort -@ 12 -o SRR579292_sorted.bam
```

Faça a indexação do arquivo BAM

```bash
samtools index SRR579292_sorted.bam
```
Gere a profundidade

```bash
jgi_summarize_bam_contig_depths --outputDepth depth.txt SRR579292_sorted.bam
```
## Executando o Metabat2
```bash
 metabat2 -i final.contigs.fa -a depth.txt -o ../../../bins/metabat/bin -t 12 --minContig 1500
```
## Executando o Maxbin2

```bash
 run_MaxBin.pl -contig final.contigs.fa -abund depth.txt -out ../../../bins/maxbin/maxbin -thread 12
```

## Arquivos e ambiente conda necessários para executar o CONCOCT
Desative o ambiente conda "binning'
```bash
conda deactivate
```
Ative o ambiente conda "concoct_env"
```bash
conda activate concoct_env
```
## Fragmentar contigs
O CONCOCT trabalha melhor quebrando contigs grandes.

```bash 
cut_up_fasta.py final.contigs.fa -c 10000 -o 0 -m -b ../../../bins/concoct/contigs_10K.bed > ../../../bins/concoct/contigs_10K.fa
```
Gere a tabela de cobertura
```bash
concoct_coverage_table.py ../../../bins/concoct/contigs_10K.bed SRR579292_sorted.bam > ../../../bins/concoct/coverage_table.tsv
```


::: callout-note
## Nota

Na chamada `kaiju-convertNR`, por padrão, são incluídas apenas sequências de Archaea, Bactérias e Vírus do NCBI-nr. Este comportamento pode ser alterado com o argumento `-l`, passando um arquivo de entrada como `~/miniconda3/envs/medusaPipeline/bin/kaiju-taxonlistEuk.tsv`. Este argumento utiliza apenas sequências com ancestrais listados no arquivo.
:::

## Realizando a classificação taxonômica

Mude o diretório atual para "Pipeline/taxonomic" e execute a classificação taxonômica:
```bash
kaiju -t db/nodes.dmp -f db/kaijuNR.fmi -i ../data/removal/unaligned_1.fastq -j ../data/removal/unaligned_2.fastq -o ../result/SRR579292_kaiju.out -z 8
```

Adicione os nomes dos táxons ao output:
```bash
kaiju-addTaxonNames -t db/nodes.dmp -n db/names.dmp -r superkingdom,phylum,class,order,family,genus,species -i ../result/SRR579292_kaiju.out -o ../result/SRR579292_kaiju.names
```

Gere os gráficos Krona:
```bash
kaiju2krona -t db/nodes.dmp -n db/names.dmp -i ../result/SRR579292_kaiju.out -o ../result/SRR579292_kaiju2krona.out
ktImportText -o ../result/SRR579292_krona.html ../result/SRR579292_kaiju2krona.out
```
